# Generated by Django 4.2.3 on 2023-08-04 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('street', models.CharField(max_length=100)),
                (
                    'house_number',
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1)
                        ]
                    ),
                ),
                (
                    'office_number',
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1)
                        ]
                    ),
                ),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='BusinessLines',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('business_line', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'business_lines',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('city', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'company_name',
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ('staff_number', models.PositiveIntegerField()),
                ('founding_year', models.SmallIntegerField()),
                ('logo', models.FileField(blank=True, upload_to='company/logo/')),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=150)),
                ('instagram', models.CharField(blank=True, max_length=150)),
                ('web_site', models.CharField(max_length=150)),
                ('twitter', models.CharField(blank=True, max_length=150)),
                (
                    'address',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='companies',
                        to='core.addresses',
                    ),
                ),
                (
                    'auth_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='companies',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Competencies',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('competence', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'competencies',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('country', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('photo', models.CharField(blank=True, max_length=150)),
                (
                    'auth_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'city',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to='core.cities',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to='core.companies',
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to='core.countries',
                    ),
                ),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmploymentFormats',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('employment_format', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'employment_formats',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='LanguageSkills',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'language',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='languages',
                        to='core.languages',
                    ),
                ),
            ],
            options={
                'db_table': 'language_skills',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='ResponseStatuses',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'response_statuses',
            },
        ),
        migrations.CreateModel(
            name='ReviewsScore',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('likes', models.BooleanField(default=False)),
                ('dislikes', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reviews_score',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('skill', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('tag', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('work_experience', models.PositiveIntegerField(null=True)),
                ('resume', models.FileField(blank=True, upload_to='users/resume/')),
                ('photo', models.FileField(blank=True, upload_to='users/photo/')),
                (
                    'experience_description',
                    models.TextField(blank=True, max_length=500),
                ),
                ('salary_min', models.PositiveIntegerField(null=True)),
                ('salary_max', models.PositiveIntegerField(null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=150)),
                ('github', models.CharField(blank=True, max_length=150)),
                (
                    'auth_user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'city',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profiles',
                        to='core.cities',
                    ),
                ),
                (
                    'competence',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users',
                        to='core.competencies',
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profiles',
                        to='core.countries',
                    ),
                ),
                (
                    'employment_formats',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users',
                        to='core.employmentformats',
                    ),
                ),
                (
                    'gender',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profiles',
                        to='core.genders',
                    ),
                ),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserStatuses',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'user_statuses',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary_min', models.PositiveIntegerField(null=True)),
                ('salary_max', models.PositiveIntegerField(null=True)),
                (
                    'competence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vacancy',
                        to='core.competencies',
                    ),
                ),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='WorkFormats',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('work_format', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'work_formats',
            },
        ),
        migrations.CreateModel(
            name='VacancyTags',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tags',
                        to='core.tags',
                    ),
                ),
                (
                    'vacancy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vacancies',
                        to='core.vacancy',
                    ),
                ),
            ],
            options={
                'db_table': 'vacancy_tags',
            },
        ),
        migrations.CreateModel(
            name='VacancyCountries',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='countries',
                        to='core.countries',
                    ),
                ),
                (
                    'vacancy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vacancy',
                        to='core.vacancy',
                    ),
                ),
            ],
            options={
                'db_table': 'vacancy_counties',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='country',
            field=models.ManyToManyField(
                through='core.VacancyCountries', to='core.countries'
            ),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vacancy',
                to='core.employees',
            ),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_formats',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vacancy',
                to='core.employmentformats',
            ),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tag',
            field=models.ManyToManyField(through='core.VacancyTags', to='core.tags'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vacancy',
                to='core.workformats',
            ),
        ),
        migrations.CreateModel(
            name='UsersTags',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='Tags',
                        to='core.tags',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='Users',
                        to='core.users',
                    ),
                ),
            ],
            options={
                'db_table': 'users_tags',
            },
        ),
        migrations.CreateModel(
            name='UsersLanguageSkills',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'language',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='LanguageSkills',
                        to='core.languageskills',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users',
                        to='core.users',
                    ),
                ),
            ],
            options={
                'db_table': 'users_language_skills',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.ManyToManyField(
                through='core.UsersLanguageSkills', to='core.languageskills'
            ),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='core.userstatuses',
            ),
        ),
        migrations.AddField(
            model_name='users',
            name='tag',
            field=models.ManyToManyField(through='core.UsersTags', to='core.tags'),
        ),
        migrations.AddField(
            model_name='users',
            name='work_format',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='core.workformats',
            ),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('review', models.TextField(max_length=800)),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='core.companies',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='core.users',
                    ),
                ),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('accompanying_text', models.TextField(max_length=500)),
                ('resume', models.CharField(max_length=150)),
                (
                    'status',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responses',
                        to='core.responsestatuses',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responses',
                        to='core.users',
                    ),
                ),
                (
                    'vacancy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responses',
                        to='core.vacancy',
                    ),
                ),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.AddField(
            model_name='languageskills',
            name='skill',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='skills',
                to='core.skills',
            ),
        ),
        migrations.AddField(
            model_name='languages',
            name='skill',
            field=models.ManyToManyField(
                through='core.LanguageSkills', to='core.skills'
            ),
        ),
        migrations.CreateModel(
            name='EmployeesPositions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employees',
                        to='core.employees',
                    ),
                ),
                (
                    'position',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='positions',
                        to='core.positions',
                    ),
                ),
            ],
            options={
                'db_table': 'employees_positions',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ManyToManyField(
                through='core.EmployeesPositions', to='core.positions'
            ),
        ),
        migrations.CreateModel(
            name='EmailConfirmationCodes',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('expiration', models.PositiveIntegerField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='emailcondirmationcodes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'emailcondirmationcodes',
            },
        ),
        migrations.CreateModel(
            name='CompaniesBusinessLines',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                (
                    'business_line',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='BusinessLines',
                        to='core.businesslines',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='companies',
                        to='core.companies',
                    ),
                ),
            ],
            options={
                'db_table': 'companies_business_lines',
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='business_lines',
            field=models.ManyToManyField(
                through='core.CompaniesBusinessLines', to='core.businesslines'
            ),
        ),
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses',
                to='core.cities',
            ),
        ),
        migrations.AddField(
            model_name='addresses',
            name='country',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses',
                to='core.countries',
            ),
        ),
        migrations.AddConstraint(
            model_name='vacancytags',
            constraint=models.UniqueConstraint(
                fields=('vacancy', 'tag'), name='unique_vacancy_tags'
            ),
        ),
        migrations.AddConstraint(
            model_name='vacancycountries',
            constraint=models.UniqueConstraint(
                fields=('vacancy', 'country'), name='unique_vacancy_counties'
            ),
        ),
        migrations.AddConstraint(
            model_name='userstags',
            constraint=models.UniqueConstraint(
                fields=('user', 'tag'), name='unique_users_tags'
            ),
        ),
        migrations.AddConstraint(
            model_name='userslanguageskills',
            constraint=models.UniqueConstraint(
                fields=('user', 'language'), name='unique_users_language_skills'
            ),
        ),
        migrations.AddConstraint(
            model_name='languageskills',
            constraint=models.UniqueConstraint(
                fields=('language', 'skill'), name='unique_language_skills'
            ),
        ),
        migrations.AddConstraint(
            model_name='employeespositions',
            constraint=models.UniqueConstraint(
                fields=('employee', 'position'), name='unique_employees_positions'
            ),
        ),
        migrations.AddConstraint(
            model_name='companiesbusinesslines',
            constraint=models.UniqueConstraint(
                fields=('company', 'business_line'),
                name='unique_companies_business_lines',
            ),
        ),
    ]
