# Generated by Django 4.2.3 on 2023-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_add_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.FileField(blank=True, upload_to='users/photo/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='resume',
            field=models.FileField(blank=True, upload_to='users/resume/'),
        ),
    ]
