# Generated by Django 4.2.3 on 2023-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_alter_users_photo_alter_users_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.FileField(blank=True, upload_to='company/logo/'),
        ),
    ]
