# Generated by Django 4.2.3 on 2023-08-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_add_user_roles_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsscore',
            name='review',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviewsscore',
                to='core.reviews',
            ),
        ),
        migrations.AddField(
            model_name='reviewsscore',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviewsscore',
                to='core.users',
            ),
        ),
    ]
