# Generated by Django 4.2.3 on 2023-07-23 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_alter_companies_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacancyCounties',
            new_name='VacancyCountries',
        ),
    ]
