# Generated by Django 4.2.3 on 2023-08-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_reviewsscore_review_reviewsscore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsscore',
            name='review',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviewsscore',
                to='core.reviews',
            ),
        ),
        migrations.AlterField(
            model_name='reviewsscore',
            name='user',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviewsscore',
                to='core.users',
            ),
            preserve_default=False,
        ),
    ]
