# Generated by Django 4.2.3 on 2023-08-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_alter_reviewsscore_review_alter_reviewsscore_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailconfirmationcodes',
            table='email_condirmation_codes',
        ),
    ]
