# Generated by Django 4.2.3 on 2023-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_alter_emailconfirmationcodes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companies',
            name='founding_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companies',
            name='staff_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='web_site',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
