# Generated by Django 4.2.3 on 2023-08-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_alter_companies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
