# Generated by Django 4.2.3 on 2023-08-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_users_name_users_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
